### PR TITLE
2 Add ZH KO EN

### PR DESCRIPTION
**Pull request by Fr-Dae**
https://github.com/Fr-Dae/hafen-client/issues/2
https://github.com/EnderWiggin/hafen-client/issues/65
with the work of  
@Vareckeska
@Cediner
@Ardenneslol
@zongxiaotao

### CODE REVIEW

**Comment by Fr-Dae** [comment]
Could you make the launcher handle accented characters correctly to avoid any crashes? 

replacing all the accents takes a very long time

**Comment by Fr-Dae** [comment]
@EnderWiggin

**Comment by EnderWiggin** [comment]
This pull request has too many changed files - please resubmit with only relevant changed files.

**Comment by EnderWiggin** [comment]
> Could you make the launcher handle accented characters correctly to avoid any crashes?
> 
> replacing all the accents takes a very long time

What's wrong with the launcher? Which (in what place) accented characters break it?

**Comment by Fr-Dae** [comment]
chmod -r 775 ./, just a update about locale read/write  right you can validate it


and why doy ou close ? you can just ask for modification , no need close

**Pull request closed without merging**
